# Generated by Django 4.2.2 on 2023-06-24 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='body',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
