# Generated by Django 4.2.2 on 2023-06-29 16:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_post_body_post_created_at_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
