# Generated by Django 4.2.2 on 2023-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
