# Generated by Django 3.2.8 on 2023-10-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='unlike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
